services:
  - type: web
    name: ecommerce
    runtime: python
    envVars:
      - key: DATABASE_URL
        value: "sqlite:////var/lib/sqlite/db.sqlite3"  # Persistent storage path
      - key: SECRET_KEY
        sync: false  # Keeps the secret key secure, manually set in Render's dashboard
      - key: DEBUG
        value: "False"  # Change to "True" only for local testing
      - key: ALLOWED_HOSTS
        value: "ecommercee-lkck.onrender.com,127.0.0.1,localhost"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin0902"
         # Set password manually in Render Dashboard
    disk:
      name: sqlite-data
      mountPath: /var/lib/sqlite  # Ensures database persistence
      sizeGB: 1  # Minimum size for persistence
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); \
      User.objects.filter(username='$DJANGO_SUPERUSER_USERNAME').exists() or \
      User.objects.create_superuser('$DJANGO_SUPERUSER_USERNAME','$DJANGO_SUPERUSER_PASSWORD')"
      gunicorn project.wsgi:application --bind 0.0.0.0:8000

    postDeployCommand: |
      python manage.py migrate --noinput  # Runs all pending migrations
      python manage.py collectstatic --noinput  # Collects static files for deployment
