# Generated by Django 5.0.7 on 2024-07-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('pasword', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='signin',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
