# Generated by Django 5.0.6 on 2024-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.TextField()),
                ('add', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='signin',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
