# Generated by Django 5.0.6 on 2024-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userregister_delete_signin_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='confirmpassword',
            field=models.CharField(default='', max_length=50),
        ),
    ]
