# Generated by Django 5.0.7 on 2024-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_userregister_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=100)),
                ('add', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('qty', models.CharField(max_length=6)),
                ('totalprice', models.CharField(max_length=50)),
                ('orderid', models.CharField(max_length=50)),
                ('transactionid', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
