# Generated by Django 5.0.7 on 2024-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paytype',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
