# Generated by Django 5.0.7 on 2024-08-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_order_paytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderid',
        ),
    ]
