# Generated by Django 5.0.7 on 2024-08-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_order_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=100)),
                ('qty', models.PositiveBigIntegerField()),
                ('totalprice', models.PositiveBigIntegerField()),
                ('orderid', models.CharField(default='0', max_length=5)),
            ],
        ),
    ]
