# Generated by Django 5.0.7 on 2024-08-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='STOCK',
        ),
    ]
