# Generated by Django 5.0.7 on 2025-01-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_rename_qty_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="productid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="userid",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default="Pending",
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default="Pending",
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.userregister",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="add",
            field=models.TextField(default="Pending"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="pincode",
            field=models.CharField(default="Pending", max_length=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="qty",
            field=models.CharField(default="Pending", max_length=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="totalprice",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="transactionid",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
