# Generated by Django 5.0.7 on 2025-01-30 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_alter_order_transactionid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="transactionid",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.userregister",
            ),
        ),
    ]
