# Generated by Django 5.0.7 on 2025-01-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_alter_order_product_alter_order_transactionid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.userregister"
            ),
        ),
    ]
