# Generated by Django 5.0.7 on 2025-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_complited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
