# Generated by Django 5.0.7 on 2025-02-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0020_order_order_complited_alter_order_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="datetime",
            new_name="order_placed",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_complited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
