# Generated by Django 5.0.7 on 2025-02-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0021_rename_datetime_order_order_placed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
